function [A,dAdx,dAdz,d2Adxz,d2Adzz] = norm4_lev(in1,in2,lev)
%NORM4_LEV
%    [A,dAdx,dAdz,d2Adxz,d2Adzz] = NORM4_LEV(IN1,IN2,LEV)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Feb-2024 09:41:16

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
z1 = in2(1,:);
z2 = in2(2,:);
t2 = cos(x3);
t3 = sin(x3);
t6 = -z1;
t7 = -z2;
t4 = t2.^2;
t5 = t3.^2;
t8 = t6+x1;
t9 = t7+x2;
t10 = t2.*t8;
t11 = t2.*t9;
t12 = t3.*t8;
t13 = t3.*t9;
t14 = -t12;
t15 = t10+t13;
t16 = t11+t14;
t17 = t15.^2;
t18 = t15.^3;
t19 = t16.^2;
A = -lev+t17.^2+t19.^2;
if nargout > 1
    t20 = t16.^3;
    t21 = t2.*t18.*4.0;
    t22 = t3.*t18.*4.0;
    t26 = t4.*t17.*1.2e+1;
    t27 = t5.*t17.*1.2e+1;
    t28 = t2.*t3.*t17.*1.2e+1;
    t23 = -t21;
    t24 = t2.*t20.*4.0;
    t25 = t3.*t20.*4.0;
    dAdx = [t21-t25,t22+t24,t16.*t18.*4.0-t15.*t20.*4.0];
end
if nargout > 2
    dAdz = [t23+t25,-t22-t24];
end
if nargout > 3
    t29 = -t28;
    t30 = t4.*t19.*1.2e+1;
    t31 = t5.*t19.*1.2e+1;
    t32 = t2.*t3.*t19.*1.2e+1;
    t33 = -t32;
    t34 = t29+t32;
    d2Adxz = reshape([-t26-t31,t34,t34,-t27-t30,t22+t24-t2.*t16.*t17.*1.2e+1-t3.*t15.*t19.*1.2e+1,t23+t25+t2.*t15.*t19.*1.2e+1-t3.*t16.*t17.*1.2e+1],[2,3]);
end
if nargout > 4
    t35 = t28+t33;
    d2Adzz = reshape([t26+t31,t35,t35,t27+t30],[2,2]);
end
end
