function [A,dAdx,dAdz,d2Adxz,d2Adzz] = offset_circle(in1,in2,in3)
%OFFSET_CIRCLE
%    [A,dAdx,dAdz,d2Adxz,d2Adzz] = OFFSET_CIRCLE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Feb-2024 09:41:15

R = in3(3,:);
p1 = in3(1,:);
p2 = in3(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
z1 = in2(1,:);
z2 = in2(2,:);
t2 = cos(x3);
t3 = sin(x3);
t6 = -z1;
t7 = -z2;
t4 = t2.^2;
t5 = t3.^2;
t10 = t6+x1;
t11 = t7+x2;
t8 = t4.*2.0;
t9 = t5.*2.0;
t14 = t2.*t10;
t15 = t2.*t11;
t16 = t3.*t10;
t17 = t3.*t11;
t12 = -t8;
t13 = -t9;
t18 = -t16;
t19 = t8+t9;
t21 = t14+t17;
t20 = t12+t13;
t22 = p1+t21;
t23 = t15+t18;
t24 = p2+t23;
A = -R.^2+t22.^2+t24.^2;
if nargout > 1
    t25 = t3.*t22.*2.0;
    t26 = t2.*t22.*2.0;
    t27 = -t26;
    t28 = t3.*t24.*2.0;
    t29 = t2.*t24.*2.0;
    dAdx = [t26-t28,t25+t29,t21.*t24.*-2.0+t22.*t23.*2.0];
end
if nargout > 2
    dAdz = [t27+t28,-t25-t29];
end
if nargout > 3
    d2Adxz = reshape([t20,0.0,0.0,t20,t25+t29-t3.*t21.*2.0-t2.*t23.*2.0,t27+t28+t2.*t21.*2.0-t3.*t23.*2.0],[2,3]);
end
if nargout > 4
    d2Adzz = reshape([t19,0.0,0.0,t19],[2,2]);
end
end
